/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthHeader: typeof import('./components/AuthHeader.vue')['default']
    copy: typeof import('./components/auth/SignInCard copy.vue')['default']
    DashboardCard: typeof import('./components/dashboard/DashboardCard.vue')['default']
    DashboardHeader: typeof import('./components/dashboard/DashboardHeader.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MainHeader: typeof import('./components/MainHeader.vue')['default']
    RolesTable: typeof import('./components/dashboard/role/RolesTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInCard: typeof import('./components/auth/SignInCard.vue')['default']
    SignUpCard: typeof import('./components/auth/SignUpCard.vue')['default']
    UsersTable: typeof import('./components/dashboard/user/UsersTable.vue')['default']
  }
}
